language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - chmod +x ${PWD}/php-cs-fixer.sh

script:
  - php vendor/bin/phpunit --coverage-text
  - ${PWD}/php-cs-fixer.sh

matrix:
  fast_finish: true