language: php

php:
  - 7.1

stages:
  - test
  - code_style

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

jobs:
  include:
    - stage: test
      script: php vendor/bin/phpunit --coverage-text
    - stage: code_style
      script:
        - chmod +x php-cs-fixer.sh
        - ./php-cs-fixer.sh
matrix:
  fast_finish: true